name: Clippy, fmt, and check

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

on:
  workflow_call:

jobs:

  check:
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Create out directory
        shell: bash
        run: mkdir -p ./out
      - name: Check the project
        working-directory: ./src-tauri
        run: |
          cargo check --workspace --all-targets --all-features

  clippy:
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Create out directory
        shell: bash
        run: mkdir -p ./out
      - name: Check lints
        working-directory: ./src-tauri
        run: |
          cargo clippy --all-targets --all-features --examples --tests

  fmt:
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt
      - name: Create out directory
        shell: bash
        run: mkdir -p ./out
      - name: Check formatting
        working-directory: ./src-tauri
        run: cargo fmt --all --check
